{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": []
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "code",
      "execution_count": 1,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "ecJsgJ7eRh8r",
        "outputId": "31b218e0-1386-4ee3-9c3e-21c52675d979"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Collecting deepface\n",
            "  Downloading deepface-0.0.93-py3-none-any.whl.metadata (30 kB)\n",
            "Requirement already satisfied: requests>=2.27.1 in /usr/local/lib/python3.11/dist-packages (from deepface) (2.32.3)\n",
            "Requirement already satisfied: numpy>=1.14.0 in /usr/local/lib/python3.11/dist-packages (from deepface) (1.26.4)\n",
            "Requirement already satisfied: pandas>=0.23.4 in /usr/local/lib/python3.11/dist-packages (from deepface) (2.2.2)\n",
            "Requirement already satisfied: gdown>=3.10.1 in /usr/local/lib/python3.11/dist-packages (from deepface) (5.2.0)\n",
            "Requirement already satisfied: tqdm>=4.30.0 in /usr/local/lib/python3.11/dist-packages (from deepface) (4.67.1)\n",
            "Requirement already satisfied: Pillow>=5.2.0 in /usr/local/lib/python3.11/dist-packages (from deepface) (11.1.0)\n",
            "Requirement already satisfied: opencv-python>=4.5.5.64 in /usr/local/lib/python3.11/dist-packages (from deepface) (4.11.0.86)\n",
            "Requirement already satisfied: tensorflow>=1.9.0 in /usr/local/lib/python3.11/dist-packages (from deepface) (2.18.0)\n",
            "Requirement already satisfied: keras>=2.2.0 in /usr/local/lib/python3.11/dist-packages (from deepface) (3.8.0)\n",
            "Requirement already satisfied: Flask>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from deepface) (3.1.0)\n",
            "Collecting flask-cors>=4.0.1 (from deepface)\n",
            "  Downloading flask_cors-5.0.1-py3-none-any.whl.metadata (961 bytes)\n",
            "Collecting mtcnn>=0.1.0 (from deepface)\n",
            "  Downloading mtcnn-1.0.0-py3-none-any.whl.metadata (5.8 kB)\n",
            "Collecting retina-face>=0.0.1 (from deepface)\n",
            "  Downloading retina_face-0.0.17-py3-none-any.whl.metadata (10 kB)\n",
            "Collecting fire>=0.4.0 (from deepface)\n",
            "  Downloading fire-0.7.0.tar.gz (87 kB)\n",
            "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m87.2/87.2 kB\u001b[0m \u001b[31m3.4 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25h  Preparing metadata (setup.py) ... \u001b[?25l\u001b[?25hdone\n",
            "Collecting gunicorn>=20.1.0 (from deepface)\n",
            "  Downloading gunicorn-23.0.0-py3-none-any.whl.metadata (4.4 kB)\n",
            "Requirement already satisfied: termcolor in /usr/local/lib/python3.11/dist-packages (from fire>=0.4.0->deepface) (2.5.0)\n",
            "Requirement already satisfied: Werkzeug>=3.1 in /usr/local/lib/python3.11/dist-packages (from Flask>=1.1.2->deepface) (3.1.3)\n",
            "Requirement already satisfied: Jinja2>=3.1.2 in /usr/local/lib/python3.11/dist-packages (from Flask>=1.1.2->deepface) (3.1.5)\n",
            "Requirement already satisfied: itsdangerous>=2.2 in /usr/local/lib/python3.11/dist-packages (from Flask>=1.1.2->deepface) (2.2.0)\n",
            "Requirement already satisfied: click>=8.1.3 in /usr/local/lib/python3.11/dist-packages (from Flask>=1.1.2->deepface) (8.1.8)\n",
            "Requirement already satisfied: blinker>=1.9 in /usr/local/lib/python3.11/dist-packages (from Flask>=1.1.2->deepface) (1.9.0)\n",
            "Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.11/dist-packages (from gdown>=3.10.1->deepface) (4.13.3)\n",
            "Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from gdown>=3.10.1->deepface) (3.17.0)\n",
            "Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from gunicorn>=20.1.0->deepface) (24.2)\n",
            "Requirement already satisfied: absl-py in /usr/local/lib/python3.11/dist-packages (from keras>=2.2.0->deepface) (1.4.0)\n",
            "Requirement already satisfied: rich in /usr/local/lib/python3.11/dist-packages (from keras>=2.2.0->deepface) (13.9.4)\n",
            "Requirement already satisfied: namex in /usr/local/lib/python3.11/dist-packages (from keras>=2.2.0->deepface) (0.0.8)\n",
            "Requirement already satisfied: h5py in /usr/local/lib/python3.11/dist-packages (from keras>=2.2.0->deepface) (3.12.1)\n",
            "Requirement already satisfied: optree in /usr/local/lib/python3.11/dist-packages (from keras>=2.2.0->deepface) (0.14.1)\n",
            "Requirement already satisfied: ml-dtypes in /usr/local/lib/python3.11/dist-packages (from keras>=2.2.0->deepface) (0.4.1)\n",
            "Requirement already satisfied: joblib>=1.4.2 in /usr/local/lib/python3.11/dist-packages (from mtcnn>=0.1.0->deepface) (1.4.2)\n",
            "Collecting lz4>=4.3.3 (from mtcnn>=0.1.0->deepface)\n",
            "  Downloading lz4-4.4.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.8 kB)\n",
            "Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas>=0.23.4->deepface) (2.8.2)\n",
            "Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas>=0.23.4->deepface) (2025.1)\n",
            "Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas>=0.23.4->deepface) (2025.1)\n",
            "Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.27.1->deepface) (3.4.1)\n",
            "Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.27.1->deepface) (3.10)\n",
            "Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.27.1->deepface) (2.3.0)\n",
            "Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.27.1->deepface) (2025.1.31)\n",
            "Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow>=1.9.0->deepface) (1.6.3)\n",
            "Requirement already satisfied: flatbuffers>=24.3.25 in /usr/local/lib/python3.11/dist-packages (from tensorflow>=1.9.0->deepface) (25.2.10)\n",
            "Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.11/dist-packages (from tensorflow>=1.9.0->deepface) (0.6.0)\n",
            "Requirement already satisfied: google-pasta>=0.1.1 in /usr/local/lib/python3.11/dist-packages (from tensorflow>=1.9.0->deepface) (0.2.0)\n",
            "Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow>=1.9.0->deepface) (18.1.1)\n",
            "Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.11/dist-packages (from tensorflow>=1.9.0->deepface) (3.4.0)\n",
            "Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.3 in /usr/local/lib/python3.11/dist-packages (from tensorflow>=1.9.0->deepface) (4.25.6)\n",
            "Requirement already satisfied: setuptools in /usr/local/lib/python3.11/dist-packages (from tensorflow>=1.9.0->deepface) (75.1.0)\n",
            "Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow>=1.9.0->deepface) (1.17.0)\n",
            "Requirement already satisfied: typing-extensions>=3.6.6 in /usr/local/lib/python3.11/dist-packages (from tensorflow>=1.9.0->deepface) (4.12.2)\n",
            "Requirement already satisfied: wrapt>=1.11.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow>=1.9.0->deepface) (1.17.2)\n",
            "Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.11/dist-packages (from tensorflow>=1.9.0->deepface) (1.70.0)\n",
            "Requirement already satisfied: tensorboard<2.19,>=2.18 in /usr/local/lib/python3.11/dist-packages (from tensorflow>=1.9.0->deepface) (2.18.0)\n",
            "Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in /usr/local/lib/python3.11/dist-packages (from tensorflow>=1.9.0->deepface) (0.37.1)\n",
            "Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.11/dist-packages (from astunparse>=1.6.0->tensorflow>=1.9.0->deepface) (0.45.1)\n",
            "Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from Jinja2>=3.1.2->Flask>=1.1.2->deepface) (3.0.2)\n",
            "Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.11/dist-packages (from tensorboard<2.19,>=2.18->tensorflow>=1.9.0->deepface) (3.7)\n",
            "Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.11/dist-packages (from tensorboard<2.19,>=2.18->tensorflow>=1.9.0->deepface) (0.7.2)\n",
            "Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.11/dist-packages (from beautifulsoup4->gdown>=3.10.1->deepface) (2.6)\n",
            "Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /usr/local/lib/python3.11/dist-packages (from requests[socks]->gdown>=3.10.1->deepface) (1.7.1)\n",
            "Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.11/dist-packages (from rich->keras>=2.2.0->deepface) (3.0.0)\n",
            "Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.11/dist-packages (from rich->keras>=2.2.0->deepface) (2.18.0)\n",
            "Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.11/dist-packages (from markdown-it-py>=2.2.0->rich->keras>=2.2.0->deepface) (0.1.2)\n",
            "Downloading deepface-0.0.93-py3-none-any.whl (108 kB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m108.6/108.6 kB\u001b[0m \u001b[31m6.7 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hDownloading flask_cors-5.0.1-py3-none-any.whl (11 kB)\n",
            "Downloading gunicorn-23.0.0-py3-none-any.whl (85 kB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m85.0/85.0 kB\u001b[0m \u001b[31m4.1 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hDownloading mtcnn-1.0.0-py3-none-any.whl (1.9 MB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m1.9/1.9 MB\u001b[0m \u001b[31m30.8 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hDownloading retina_face-0.0.17-py3-none-any.whl (25 kB)\n",
            "Downloading lz4-4.4.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.3 MB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m1.3/1.3 MB\u001b[0m \u001b[31m27.4 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hBuilding wheels for collected packages: fire\n",
            "  Building wheel for fire (setup.py) ... \u001b[?25l\u001b[?25hdone\n",
            "  Created wheel for fire: filename=fire-0.7.0-py3-none-any.whl size=114249 sha256=5385c53a2b9d1ff3a82bc5590675b7d0308eaa9b42273226026857e79b1176af\n",
            "  Stored in directory: /root/.cache/pip/wheels/46/54/24/1624fd5b8674eb1188623f7e8e17cdf7c0f6c24b609dfb8a89\n",
            "Successfully built fire\n",
            "Installing collected packages: lz4, gunicorn, fire, mtcnn, flask-cors, retina-face, deepface\n",
            "Successfully installed deepface-0.0.93 fire-0.7.0 flask-cors-5.0.1 gunicorn-23.0.0 lz4-4.4.4 mtcnn-1.0.0 retina-face-0.0.17\n"
          ]
        }
      ],
      "source": [
        "!pip install deepface"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "import os\n",
        "import pandas as pd\n",
        "from deepface import DeepFace\n",
        "\n",
        "def generate_combined_dataset(input_folder, output_file, model_name=\"ArcFace\"):\n",
        "\n",
        "\n",
        "    data = []\n",
        "\n",
        "\n",
        "    for label in os.listdir(input_folder):\n",
        "        label_path = os.path.join(input_folder, label)\n",
        "        if os.path.isdir(label_path):\n",
        "            for file in os.listdir(label_path):\n",
        "                file_path = os.path.join(label_path, file)\n",
        "                if file.endswith(('.jpg', '.png', '.jpeg')):\n",
        "                    try:\n",
        "\n",
        "                        embedding_objs = DeepFace.represent(img_path=file_path, model_name=model_name)\n",
        "                        features = embedding_objs[0]['embedding']\n",
        "\n",
        "\n",
        "                        row = [label, file] + features\n",
        "                        data.append(row)\n",
        "                    except Exception as e:\n",
        "                        print(f\"Error processing {file_path}: {e}\")\n",
        "\n",
        "\n",
        "    if data:\n",
        "        columns = ['label', 'file_name'] + [f'feature{i+1}' for i in range(len(data[0]) - 2)]\n",
        "        dataset = pd.DataFrame(data, columns=columns)\n",
        "\n",
        "\n",
        "        dataset.to_csv(output_file, index=False)\n",
        "        print(f\"Combined dataset saved to {output_file}\")\n",
        "    else:\n",
        "        print(f\"No valid images found in the directory: {input_folder}\")\n",
        "\n",
        "\n",
        "input_folder = \"/content/drive/MyDrive/dataset/persian_dataset\"\n",
        "output_file = \"combined_dataset.csv\"\n",
        "generate_combined_dataset(input_folder, output_file, model_name=\"ArcFace\")\n"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "RRpzjBUUSNHB",
        "outputId": "5c0d1317-829f-4e2a-c765-6787cdd46bf6"
      },
      "execution_count": 2,
      "outputs": [
        {
          "metadata": {
            "tags": null
          },
          "name": "stdout",
          "output_type": "stream",
          "text": [
            "25-04-15 09:08:03 - Directory /root/.deepface has been created\n",
            "25-04-15 09:08:03 - Directory /root/.deepface/weights has been created\n",
            "25-04-15 09:08:07 - arcface_weights.h5 will be downloaded to /root/.deepface/weights/arcface_weights.h5\n"
          ]
        },
        {
          "metadata": {
            "tags": null
          },
          "name": "stderr",
          "output_type": "stream",
          "text": [
            "Downloading...\n",
            "From: https://github.com/serengil/deepface_models/releases/download/v1.0/arcface_weights.h5\n",
            "To: /root/.deepface/weights/arcface_weights.h5\n",
            "100%|██████████| 137M/137M [00:00<00:00, 203MB/s]\n"
          ]
        },
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Error processing /content/drive/MyDrive/dataset/persian_dataset/Parinaz_Izadyar/maxresdefault (1)-1.jpg: Face could not be detected in /content/drive/MyDrive/dataset/persian_dataset/Parinaz_Izadyar/maxresdefault (1)-1.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.\n",
            "Error processing /content/drive/MyDrive/dataset/persian_dataset/Siavash_Ghomayshi/035df88438735a528a15a55c18456a4a-1.jpg: Face could not be detected in /content/drive/MyDrive/dataset/persian_dataset/Siavash_Ghomayshi/035df88438735a528a15a55c18456a4a-1.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.\n",
            "Error processing /content/drive/MyDrive/dataset/persian_dataset/Siavash_Ghomayshi/5dc50ee63f0c0-0.jpg: Face could not be detected in /content/drive/MyDrive/dataset/persian_dataset/Siavash_Ghomayshi/5dc50ee63f0c0-0.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.\n",
            "Error processing /content/drive/MyDrive/dataset/persian_dataset/Siavash_Ghomayshi/Siavash-Ghomayshi-Gozasht-0.jpg: Face could not be detected in /content/drive/MyDrive/dataset/persian_dataset/Siavash_Ghomayshi/Siavash-Ghomayshi-Gozasht-0.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.\n",
            "Error processing /content/drive/MyDrive/dataset/persian_dataset/Siamak_Ansari/3936-2.jpg: Face could not be detected in /content/drive/MyDrive/dataset/persian_dataset/Siamak_Ansari/3936-2.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.\n",
            "Error processing /content/drive/MyDrive/dataset/persian_dataset/Siamak_Ansari/5557474-0.jpg: Face could not be detected in /content/drive/MyDrive/dataset/persian_dataset/Siamak_Ansari/5557474-0.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.\n",
            "Error processing /content/drive/MyDrive/dataset/persian_dataset/Parviz_Parastooee/AndroidOnlineNewsImage+(15)-2.jpg: Face could not be detected in /content/drive/MyDrive/dataset/persian_dataset/Parviz_Parastooee/AndroidOnlineNewsImage+(15)-2.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.\n",
            "Error processing /content/drive/MyDrive/dataset/persian_dataset/Parviz_Parastooee/1397072414114060215669924-5.jpg: Face could not be detected in /content/drive/MyDrive/dataset/persian_dataset/Parviz_Parastooee/1397072414114060215669924-5.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.\n",
            "Error processing /content/drive/MyDrive/dataset/persian_dataset/Parviz_Parastooee/6708313_275_0_936_661_1920x0_80_0_0_365084393b7cfe3b61c1dc64fea9807b-1.jpg: Face could not be detected in /content/drive/MyDrive/dataset/persian_dataset/Parviz_Parastooee/6708313_275_0_936_661_1920x0_80_0_0_365084393b7cfe3b61c1dc64fea9807b-1.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.\n",
            "Error processing /content/drive/MyDrive/dataset/persian_dataset/Parviz_Parastooee/parviz-shabnak.ir-1-1.jpg: Face could not be detected in /content/drive/MyDrive/dataset/persian_dataset/Parviz_Parastooee/parviz-shabnak.ir-1-1.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.\n",
            "Error processing /content/drive/MyDrive/dataset/persian_dataset/Parviz_Parastooee/ze64beqzecxu-2.jpg: Face could not be detected in /content/drive/MyDrive/dataset/persian_dataset/Parviz_Parastooee/ze64beqzecxu-2.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.\n",
            "Error processing /content/drive/MyDrive/dataset/persian_dataset/Parviz_Parastooee/ff3191526628d30fef7be98651139981--iranian-0.jpg: Face could not be detected in /content/drive/MyDrive/dataset/persian_dataset/Parviz_Parastooee/ff3191526628d30fef7be98651139981--iranian-0.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.\n",
            "Error processing /content/drive/MyDrive/dataset/persian_dataset/Parsa_Pirozfar/35.jpg: Face could not be detected in /content/drive/MyDrive/dataset/persian_dataset/Parsa_Pirozfar/35.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.\n",
            "Error processing /content/drive/MyDrive/dataset/persian_dataset/Javad_Khiabani/283433_193-5.jpg: Face could not be detected in /content/drive/MyDrive/dataset/persian_dataset/Javad_Khiabani/283433_193-5.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.\n",
            "Error processing /content/drive/MyDrive/dataset/persian_dataset/Javad_Khiabani/Javad_Khiabani-6-1.jpg: Face could not be detected in /content/drive/MyDrive/dataset/persian_dataset/Javad_Khiabani/Javad_Khiabani-6-1.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.\n",
            "Error processing /content/drive/MyDrive/dataset/persian_dataset/Javad_Khiabani/maxresdefault (1)-1.jpg: Face could not be detected in /content/drive/MyDrive/dataset/persian_dataset/Javad_Khiabani/maxresdefault (1)-1.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.\n",
            "Error processing /content/drive/MyDrive/dataset/persian_dataset/Javad_Khiabani/hashiye_va_havashi_1630751657-0.jpg: Face could not be detected in /content/drive/MyDrive/dataset/persian_dataset/Javad_Khiabani/hashiye_va_havashi_1630751657-0.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.\n",
            "Error processing /content/drive/MyDrive/dataset/persian_dataset/Javad_Khiabani/fdert.jpg: Face could not be detected in /content/drive/MyDrive/dataset/persian_dataset/Javad_Khiabani/fdert.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.\n",
            "Error processing /content/drive/MyDrive/dataset/persian_dataset/Hootan_Shakiba/58.png: Face could not be detected in /content/drive/MyDrive/dataset/persian_dataset/Hootan_Shakiba/58.png.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.\n",
            "Error processing /content/drive/MyDrive/dataset/persian_dataset/Hootan_Shakiba/40.png: Face could not be detected in /content/drive/MyDrive/dataset/persian_dataset/Hootan_Shakiba/40.png.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.\n",
            "Error processing /content/drive/MyDrive/dataset/persian_dataset/Mehran_Modiri/poil.jpg: Face could not be detected in /content/drive/MyDrive/dataset/persian_dataset/Mehran_Modiri/poil.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.\n",
            "Error processing /content/drive/MyDrive/dataset/persian_dataset/Mehran_Modiri/fghjk.jpg: Face could not be detected in /content/drive/MyDrive/dataset/persian_dataset/Mehran_Modiri/fghjk.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.\n",
            "Error processing /content/drive/MyDrive/dataset/persian_dataset/Mehran_Ghafourian/310189_737-0.jpg: Face could not be detected in /content/drive/MyDrive/dataset/persian_dataset/Mehran_Ghafourian/310189_737-0.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.\n",
            "Error processing /content/drive/MyDrive/dataset/persian_dataset/Mehran_Ghafourian/3305179_635-0.jpg: Face could not be detected in /content/drive/MyDrive/dataset/persian_dataset/Mehran_Ghafourian/3305179_635-0.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.\n",
            "Error processing /content/drive/MyDrive/dataset/persian_dataset/Mehran_Ghafourian/434840_266-2.jpg: Face could not be detected in /content/drive/MyDrive/dataset/persian_dataset/Mehran_Ghafourian/434840_266-2.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.\n",
            "Error processing /content/drive/MyDrive/dataset/persian_dataset/Mehran_Ghafourian/Photo_1608010554274-1.jpg: Face could not be detected in /content/drive/MyDrive/dataset/persian_dataset/Mehran_Ghafourian/Photo_1608010554274-1.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.\n",
            "Error processing /content/drive/MyDrive/dataset/persian_dataset/Mehran_Ghafourian/kjl.jpg: Face could not be detected in /content/drive/MyDrive/dataset/persian_dataset/Mehran_Ghafourian/kjl.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.\n",
            "Error processing /content/drive/MyDrive/dataset/persian_dataset/Leyla_Hatami/Leyla-Hatami-98_01.jpg: Face could not be detected in /content/drive/MyDrive/dataset/persian_dataset/Leyla_Hatami/Leyla-Hatami-98_01.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.\n",
            "Error processing /content/drive/MyDrive/dataset/persian_dataset/Javad_Razavian/maxresdefault (3)-1.jpg: Face could not be detected in /content/drive/MyDrive/dataset/persian_dataset/Javad_Razavian/maxresdefault (3)-1.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.\n",
            "Error processing /content/drive/MyDrive/dataset/persian_dataset/Javad_Razavian/sjvrzv-pedar-photokade-2-0.jpg: Face could not be detected in /content/drive/MyDrive/dataset/persian_dataset/Javad_Razavian/sjvrzv-pedar-photokade-2-0.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.\n",
            "Error processing /content/drive/MyDrive/dataset/persian_dataset/Javad_Razavian/46dbf513c2b3d11332a68ff1d035c7dd-1.jpg: Face could not be detected in /content/drive/MyDrive/dataset/persian_dataset/Javad_Razavian/46dbf513c2b3d11332a68ff1d035c7dd-1.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.\n",
            "Error processing /content/drive/MyDrive/dataset/persian_dataset/Javad_Razavian/ty.jpg: Face could not be detected in /content/drive/MyDrive/dataset/persian_dataset/Javad_Razavian/ty.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.\n",
            "Error processing /content/drive/MyDrive/dataset/persian_dataset/Mohsen_Chavoshi/nody-عکس-محسن-چاوشي-1624402405-1.jpg: Input image must not have non-english characters - /content/drive/MyDrive/dataset/persian_dataset/Mohsen_Chavoshi/nody-عکس-محسن-چاوشي-1624402405-1.jpg\n",
            "Error processing /content/drive/MyDrive/dataset/persian_dataset/Mohsen_Chavoshi/nody-عکس-محسن-چاوشي-1624402405-0.jpg: Input image must not have non-english characters - /content/drive/MyDrive/dataset/persian_dataset/Mohsen_Chavoshi/nody-عکس-محسن-چاوشي-1624402405-0.jpg\n",
            "Error processing /content/drive/MyDrive/dataset/persian_dataset/Mahnaz_Afshar/116642807_116793190121794_4323068666237203778_n-0.jpg: Face could not be detected in /content/drive/MyDrive/dataset/persian_dataset/Mahnaz_Afshar/116642807_116793190121794_4323068666237203778_n-0.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.\n",
            "Error processing /content/drive/MyDrive/dataset/persian_dataset/Mahnaz_Afshar/659537_571-0.jpg: Face could not be detected in /content/drive/MyDrive/dataset/persian_dataset/Mahnaz_Afshar/659537_571-0.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.\n",
            "Error processing /content/drive/MyDrive/dataset/persian_dataset/Mahnaz_Afshar/nbghj.jpg: Face could not be detected in /content/drive/MyDrive/dataset/persian_dataset/Mahnaz_Afshar/nbghj.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.\n",
            "Error processing /content/drive/MyDrive/dataset/persian_dataset/Hamid_Lolaei/photo-hamid-lolaei-2-2.jpg: Face could not be detected in /content/drive/MyDrive/dataset/persian_dataset/Hamid_Lolaei/photo-hamid-lolaei-2-2.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.\n",
            "Error processing /content/drive/MyDrive/dataset/persian_dataset/Hamid_Lolaei/560546_111-1.jpg: Face could not be detected in /content/drive/MyDrive/dataset/persian_dataset/Hamid_Lolaei/560546_111-1.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.\n",
            "Error processing /content/drive/MyDrive/dataset/persian_dataset/Hamid_Lolaei/kloi.jpg: Face could not be detected in /content/drive/MyDrive/dataset/persian_dataset/Hamid_Lolaei/kloi.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.\n",
            "Error processing /content/drive/MyDrive/dataset/persian_dataset/Dariush_Arjmand/14000228104847864227990510-0.jpg: Face could not be detected in /content/drive/MyDrive/dataset/persian_dataset/Dariush_Arjmand/14000228104847864227990510-0.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.\n",
            "Error processing /content/drive/MyDrive/dataset/persian_dataset/Dariush_Arjmand/18787923-8372-b__6550-0.jpg: Face could not be detected in /content/drive/MyDrive/dataset/persian_dataset/Dariush_Arjmand/18787923-8372-b__6550-0.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.\n",
            "Error processing /content/drive/MyDrive/dataset/persian_dataset/Dariush_Arjmand/322838_237-3.jpg: Face could not be detected in /content/drive/MyDrive/dataset/persian_dataset/Dariush_Arjmand/322838_237-3.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.\n",
            "Error processing /content/drive/MyDrive/dataset/persian_dataset/Dariush_Arjmand/4596131-0.jpg: Face could not be detected in /content/drive/MyDrive/dataset/persian_dataset/Dariush_Arjmand/4596131-0.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.\n",
            "Error processing /content/drive/MyDrive/dataset/persian_dataset/Dariush_Arjmand/ac-image-v91627145644ee-0.jpg: Face could not be detected in /content/drive/MyDrive/dataset/persian_dataset/Dariush_Arjmand/ac-image-v91627145644ee-0.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.\n",
            "Error processing /content/drive/MyDrive/dataset/persian_dataset/Dariush_Arjmand/sdwert.jpg: Face could not be detected in /content/drive/MyDrive/dataset/persian_dataset/Dariush_Arjmand/sdwert.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.\n",
            "Error processing /content/drive/MyDrive/dataset/persian_dataset/Dariush_Arjmand/ertyui.jpg: Face could not be detected in /content/drive/MyDrive/dataset/persian_dataset/Dariush_Arjmand/ertyui.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.\n",
            "Error processing /content/drive/MyDrive/dataset/persian_dataset/Behnam_Bani/Behnam-Bani-56_01.jpg: Face could not be detected in /content/drive/MyDrive/dataset/persian_dataset/Behnam_Bani/Behnam-Bani-56_01.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.\n",
            "Error processing /content/drive/MyDrive/dataset/persian_dataset/Behnam_Bani/Behnam-Bani-38_01.jpg: Face could not be detected in /content/drive/MyDrive/dataset/persian_dataset/Behnam_Bani/Behnam-Bani-38_01.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.\n",
            "Error processing /content/drive/MyDrive/dataset/persian_dataset/Behnam_Bani/Behnam-Bani-47_01.jpg: Face could not be detected in /content/drive/MyDrive/dataset/persian_dataset/Behnam_Bani/Behnam-Bani-47_01.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.\n",
            "Error processing /content/drive/MyDrive/dataset/persian_dataset/Behnam_Bani/Behnam-Bani-99_01.jpg: Face could not be detected in /content/drive/MyDrive/dataset/persian_dataset/Behnam_Bani/Behnam-Bani-99_01.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.\n",
            "Error processing /content/drive/MyDrive/dataset/persian_dataset/Behnam_Bani/Behnam-Bani-35_01.jpg: Face could not be detected in /content/drive/MyDrive/dataset/persian_dataset/Behnam_Bani/Behnam-Bani-35_01.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.\n",
            "Error processing /content/drive/MyDrive/dataset/persian_dataset/Behnam_Bani/Behnam-Bani-98_01.jpg: Face could not be detected in /content/drive/MyDrive/dataset/persian_dataset/Behnam_Bani/Behnam-Bani-98_01.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.\n",
            "Error processing /content/drive/MyDrive/dataset/persian_dataset/Behnam_Bani/Behnam-Bani-34_01.jpg: Face could not be detected in /content/drive/MyDrive/dataset/persian_dataset/Behnam_Bani/Behnam-Bani-34_01.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.\n",
            "Error processing /content/drive/MyDrive/dataset/persian_dataset/Ebi/file2Fmedia2Fimage2Foriginal2F2223-2-0.jpg: Face could not be detected in /content/drive/MyDrive/dataset/persian_dataset/Ebi/file2Fmedia2Fimage2Foriginal2F2223-2-0.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.\n",
            "Error processing /content/drive/MyDrive/dataset/persian_dataset/Ebi/1593719730_M5kA4-0.jpg: Face could not be detected in /content/drive/MyDrive/dataset/persian_dataset/Ebi/1593719730_M5kA4-0.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.\n",
            "Error processing /content/drive/MyDrive/dataset/persian_dataset/Ebi/9008813-8244-b__5555-0.jpg: Face could not be detected in /content/drive/MyDrive/dataset/persian_dataset/Ebi/9008813-8244-b__5555-0.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.\n",
            "Error processing /content/drive/MyDrive/dataset/persian_dataset/Ebi/Bu3J9avCYAA1juE-0.jpg: Face could not be detected in /content/drive/MyDrive/dataset/persian_dataset/Ebi/Bu3J9avCYAA1juE-0.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.\n",
            "Error processing /content/drive/MyDrive/dataset/persian_dataset/Ebi/Ebi-Nazy-Naz-Kon-Pichak-Live-0.jpg: Face could not be detected in /content/drive/MyDrive/dataset/persian_dataset/Ebi/Ebi-Nazy-Naz-Kon-Pichak-Live-0.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.\n",
            "Error processing /content/drive/MyDrive/dataset/persian_dataset/Ebi/ei_thumb-1.jpg: Face could not be detected in /content/drive/MyDrive/dataset/persian_dataset/Ebi/ei_thumb-1.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.\n",
            "Error processing /content/drive/MyDrive/dataset/persian_dataset/Ebi/_112295165_photo-2020-05-15-17-04-36-4.jpg: Face could not be detected in /content/drive/MyDrive/dataset/persian_dataset/Ebi/_112295165_photo-2020-05-15-17-04-36-4.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.\n",
            "Error processing /content/drive/MyDrive/dataset/persian_dataset/Ehsan_Alikhani/22143436-2453-b__1483-1.jpg: Face could not be detected in /content/drive/MyDrive/dataset/persian_dataset/Ehsan_Alikhani/22143436-2453-b__1483-1.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.\n",
            "Error processing /content/drive/MyDrive/dataset/persian_dataset/Elham_Hamidi/320735811629964987-0.jpg: Face could not be detected in /content/drive/MyDrive/dataset/persian_dataset/Elham_Hamidi/320735811629964987-0.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.\n",
            "Error processing /content/drive/MyDrive/dataset/persian_dataset/Elham_Hamidi/elham hamidi 2-0.jpg: Face could not be detected in /content/drive/MyDrive/dataset/persian_dataset/Elham_Hamidi/elham hamidi 2-0.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.\n",
            "Error processing /content/drive/MyDrive/dataset/persian_dataset/Elham_Hamidi/mkjui (1).jpg: Face could not be detected in /content/drive/MyDrive/dataset/persian_dataset/Elham_Hamidi/mkjui (1).jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.\n",
            "Error processing /content/drive/MyDrive/dataset/persian_dataset/Bahram_Radan/Bahram Radan (39).jpg: Face could not be detected in /content/drive/MyDrive/dataset/persian_dataset/Bahram_Radan/Bahram Radan (39).jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.\n",
            "Error processing /content/drive/MyDrive/dataset/persian_dataset/Adel_FerdowsiPour/109924-0.jpg: Face could not be detected in /content/drive/MyDrive/dataset/persian_dataset/Adel_FerdowsiPour/109924-0.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.\n",
            "Error processing /content/drive/MyDrive/dataset/persian_dataset/Adel_FerdowsiPour/asdff.jpg: Face could not be detected in /content/drive/MyDrive/dataset/persian_dataset/Adel_FerdowsiPour/asdff.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.\n",
            "Error processing /content/drive/MyDrive/dataset/persian_dataset/Adel_FerdowsiPour/456987.jpg: Face could not be detected in /content/drive/MyDrive/dataset/persian_dataset/Adel_FerdowsiPour/456987.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.\n",
            "Error processing /content/drive/MyDrive/dataset/persian_dataset/Ali_Daei/17338100_303-0.jpg: Face could not be detected in /content/drive/MyDrive/dataset/persian_dataset/Ali_Daei/17338100_303-0.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.\n",
            "Error processing /content/drive/MyDrive/dataset/persian_dataset/Ali_Khamenei/Ali-Khamenei-96_01.jpg: Face could not be detected in /content/drive/MyDrive/dataset/persian_dataset/Ali_Khamenei/Ali-Khamenei-96_01.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.\n",
            "Error processing /content/drive/MyDrive/dataset/persian_dataset/Ali_Khamenei/Ali-Khamenei-05_01.jpg: Face could not be detected in /content/drive/MyDrive/dataset/persian_dataset/Ali_Khamenei/Ali-Khamenei-05_01.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.\n",
            "Error processing /content/drive/MyDrive/dataset/persian_dataset/Ali_Khamenei/Ali-Khamenei-53_01.jpg: Face could not be detected in /content/drive/MyDrive/dataset/persian_dataset/Ali_Khamenei/Ali-Khamenei-53_01.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.\n",
            "Error processing /content/drive/MyDrive/dataset/persian_dataset/Ali_Khamenei/Ali-Khamenei-61_01.jpg: Face could not be detected in /content/drive/MyDrive/dataset/persian_dataset/Ali_Khamenei/Ali-Khamenei-61_01.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.\n",
            "Error processing /content/drive/MyDrive/dataset/persian_dataset/Ali_Khamenei/Ali-Khamenei-81_01.jpg: Face could not be detected in /content/drive/MyDrive/dataset/persian_dataset/Ali_Khamenei/Ali-Khamenei-81_01.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.\n",
            "Error processing /content/drive/MyDrive/dataset/persian_dataset/Ali_Khamenei/Ali-Khamenei-02_01.jpg: Face could not be detected in /content/drive/MyDrive/dataset/persian_dataset/Ali_Khamenei/Ali-Khamenei-02_01.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.\n",
            "Error processing /content/drive/MyDrive/dataset/persian_dataset/Ali_Khamenei/Ali-Khamenei-70_01.jpg: Face could not be detected in /content/drive/MyDrive/dataset/persian_dataset/Ali_Khamenei/Ali-Khamenei-70_01.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.\n",
            "Error processing /content/drive/MyDrive/dataset/persian_dataset/Ali_Khamenei/Ali-Khamenei-13_01.jpg: Face could not be detected in /content/drive/MyDrive/dataset/persian_dataset/Ali_Khamenei/Ali-Khamenei-13_01.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.\n",
            "Error processing /content/drive/MyDrive/dataset/persian_dataset/Ali_Khamenei/Ali-Khamenei-12_01.jpg: Face could not be detected in /content/drive/MyDrive/dataset/persian_dataset/Ali_Khamenei/Ali-Khamenei-12_01.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.\n",
            "Error processing /content/drive/MyDrive/dataset/persian_dataset/Ali_Khamenei/Ali-Khamenei-67_01.jpg: Face could not be detected in /content/drive/MyDrive/dataset/persian_dataset/Ali_Khamenei/Ali-Khamenei-67_01.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.\n",
            "Error processing /content/drive/MyDrive/dataset/persian_dataset/Bahare_Rahnama/maxresdefault-2.jpg: Face could not be detected in /content/drive/MyDrive/dataset/persian_dataset/Bahare_Rahnama/maxresdefault-2.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.\n",
            "Error processing /content/drive/MyDrive/dataset/persian_dataset/Asghar_Farhadi/asgharfarhadikhatere-0.jpg: Face could not be detected in /content/drive/MyDrive/dataset/persian_dataset/Asghar_Farhadi/asgharfarhadikhatere-0.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.\n",
            "Error processing /content/drive/MyDrive/dataset/persian_dataset/Asghar_Farhadi/0tofkbt7fwd6-0.jpg: Face could not be detected in /content/drive/MyDrive/dataset/persian_dataset/Asghar_Farhadi/0tofkbt7fwd6-0.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.\n",
            "Error processing /content/drive/MyDrive/dataset/persian_dataset/Asghar_Farhadi/58254196_303-0.jpg: Face could not be detected in /content/drive/MyDrive/dataset/persian_dataset/Asghar_Farhadi/58254196_303-0.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.\n",
            "Combined dataset saved to combined_dataset.csv\n"
          ]
        }
      ]
    }
  ]
}